# Generated by Django 2.2 on 2020-11-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
