# Generated by Django 2.2 on 2020-11-08 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_remove_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=45)),
                ('chest_a', models.CharField(max_length=45)),
                ('chest_b', models.CharField(max_length=45)),
                ('chest_c', models.CharField(max_length=45)),
                ('back_a', models.CharField(max_length=45)),
                ('back_b', models.CharField(max_length=45)),
                ('back_c', models.CharField(max_length=45)),
                ('legs_a', models.CharField(max_length=45)),
                ('legs_b', models.CharField(max_length=45)),
                ('legs_c', models.CharField(max_length=45)),
                ('arms_a', models.CharField(max_length=45)),
                ('arms_b', models.CharField(max_length=45)),
                ('arms_c', models.CharField(max_length=45)),
                ('completed_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('routine_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines_crated', to='fitness_app.User')),
                ('routines_added_by', models.ManyToManyField(related_name='routine_added', to='fitness_app.User')),
            ],
        ),
    ]
